# Generated by Django 4.2.13 on 2024-06-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=16, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('delayed', 'Delayed')], default='created', max_length=16)),
            ],
        ),
    ]
