# Generated by Django 4.2.13 on 2024-06-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cpu',
            new_name='sku',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='item', max_length=256),
            preserve_default=False,
        ),
    ]
