# Generated by Django 4.2.13 on 2024-06-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_cpu_order_sku_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(db_index=True),
        ),
    ]
